### ISSUE TITLE
No artifacts found in run

### ISSUE THREAD

**Issue by charlessolar** [dorny/test-reporter#116]
Attempting to use this to get my test results posted - but seeing this warning
![image](https://user-images.githubusercontent.com/1750226/118593527-79571300-b76d-11eb-85ca-989d3266098f.png)

despite my artifacts existing?

![image](https://user-images.githubusercontent.com/1750226/118593564-8b38b600-b76d-11eb-9526-cbc0a4845fa7.png)

Heres part of my yaml

```
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: binaries
          path: artifacts/bin
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-reports
          path: artifacts/test-reports
      - uses: actions/upload-artifact@v2
        with:
          name: nugets
          path: artifacts/nuget

      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          artifact: test-reports
          name: Tests
          path: "*.trx"
          reporter: dotnet-trx
          token: ${{ secrets.REPORT_TOKEN }}
```

should I add a sleep or something before trying to reporter?

Confused what might be going on here - [Ive been playing with it here](https://github.com/charlessolar/Aggregates.NET/blob/master/.github/workflows/main.yml) but just cant get it working

**Comment by dorny** [comment]
Hi @charlessolar!

You don't need to use artifacts at all. Your test result files are available locally so this should work:
```
- uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests
          path: "artifacts/test-reports/*.trx"
          reporter: dotnet-trx
          token: ${{ secrets.REPORT_TOKEN }}
```

Fetching result files from artifacts works only when `test-reporter` is executed from a different workflow than the one where artifacts were created. Here is the [example](https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories). In case you have only one workflow, but multiple jobs, you can use `actions/download-artifact@v2` to first download files locally.

**Explanation:**
GitHub actually has two different APIs to work with artifacts.
One used by `upload-artifact` or `download-artifact` is internal and undocumented. This API has access to uploaded files while workflow is still being executed.

Then there is an official artifacts [REST API](https://docs.github.com/en/rest/reference/actions#artifacts). This API shows uploaded files only after workflow is completed. So no matter how much `sleep` you would add - it's just not possible to get the artifacts in the same workflow as they were created. As you can guess - this action uses the official API to support multi-workflow use-cases (because of security in public repos). In a single workflow setup, you have to use local file system. Either the result files are already there or you can get it there with `download-artifact` action.
