### ISSUE TITLE
fatal: Not a git repository

### ISSUE THREAD

**Issue by PaulDMendoza** [dorny/test-reporter#131]
I'm not sure why but I'm getting this error. 

![image](https://user-images.githubusercontent.com/1039795/125377158-50a06380-e341-11eb-87bd-d2e3e4a06017.png)

My build script is a bit long so copying and pasting it all of here seems uneeded. 

```
name: Tests

on:
  - push
  - pull_request
jobs:  
  test:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    strategy:
      matrix:
        dotnet-version:
          - 2.1.x
    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          POSTGRES_PASSWORD: '111+++'
          POSTGRES_DB: sigparser        
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      ...
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup .NET Core SDK ${{ matrix.dotnet-version }}'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '${{ matrix.dotnet-version }}'
      - name: Install dependencies
        run: dotnet restore
      - name: Run Migrations
        run: > 
          dotnet run 
          --project ./DBUpgrader/DBUpgrader.csproj 
          -- migrate  
          --recreate true
          --fillconfigkeytable true 
          --trycreateifnotexists true 
      - name: What directory are we in?
        run: pwd
      - name: Test
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1.5.0
        if: always()
        with:
          name: Test Results
          path: ./**/TestResults/*.trx
          reporter: 'dotnet-trx'
  

```

**Comment by dorny** [comment]
Well, this is really weird.

This action uses git to get a list of your tracked source files. For failed tests, it looks at the stack trace and the list of tracked files. The first row in the stack trace that points to any of tracked files is where the annotation will be created.

In your case, I see two possible errors:

1. Working directory when `test-reporter` is executed doesn't point to the folder where your repository is checked out
2. The `.git` folder got deleted somehow and your working directory is not a git repository.

I would recommend checking the working directory and the existence of the `.git` folder.
In case, the working directory is wrong, you could set it using `working-directory` input variable.

**Comment by PaulDMendoza** [comment]
I figured it out. I had to add **git init** after I checked out the code. 

```
steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Run git init
        run: git init
```
