### ISSUE TITLE
How to access the output parameters to notify them in Teams

### ISSUE THREAD

**Issue by ujjwala535** [dorny/test-reporter#135]
Can you please let me know how to access the output parameters to notify them in Teams channel

**Comment by jozefizso** [comment]
To access output parameters from the `dorny/test-reporter` action and use them in subsequent steps (e.g., for sending notifications to a Teams channel), you can use the `id` of the action step and reference its `outputs` properties.

Here’s an example workflow snippet that demonstrates how to do this:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests and generate report
        id: test-report
        uses: dorny/test-reporter@v2
        with:
          name: Jest Tests
          path: reports/jest-*.xml
          reporter: jest-junit

      - name: Notify to Teams
        run: |
          # Implement Teams notifications logic
          echo "Tests outcome: ${{ steps.test-report.outputs.conclusion }}"
          echo "Report URL: ${{ steps.test-report.outputs.report-url }}"
```

## References 

List of output parameters is documented in our README: https://github.com/dorny/test-reporter#output-parameters

[GitHub Actions documentation: Passing information between jobs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs)
