### ISSUE TITLE
Can't find the artifact

### ISSUE THREAD

**Issue by ghost** [dorny/test-reporter#138]
I always can't get the error mention can't find the artifact
here is my ci.yml
```
name: 'CI'

on:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
      - run: npm run test4
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: daily-test-results
          path: 'daily-test-results.json'
```
dailytest.json
```
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
      - run: npm run test4

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: daily-test-results
          path: daily-test-results.json

      - name: Daily tests report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          artifact: daily-test-results
          name: daily-test-results
          path: 'artifacts\daily-test-results.json'
          reporter: mocha-json
          only-summary: 'false'
          list-suites: 'all'
          list-tests: 'all'
```
I need help hand on this issue
