### ISSUE TITLE
Using mochawesome

### ISSUE THREAD

**Issue by yonatanaftali** [dorny/test-reporter#147]
Hey,

Can I use my mochawesome.json file with this action? I tried using it with the mocha setting, but it doesn't work. I'm getting the error `mocha.passes is not iterable` for the following configuration:
```
      - name: Report E2E Results
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@v1
        with:
          name: E2E Tests Results
          path: test/e2e/report/mochawesome.json
          reporter: mocha-json
```
