### ISSUE TITLE
Enable PAT for authentication

### ISSUE THREAD

**Issue by crizzis-unordinal** [dorny/test-reporter#150]
Trying to run `test-reporter` locally using nectos/act with a personal access token results in: 

```
| Creating check run Tests
[Test/run_tests]   ❓  ::endgroup::
[Test/run_tests]   ❗  ::error::You must authenticate via a GitHub App.
[Test/run_tests]   ❌  Failure - Test report
```

I imagine this is because creating the check run necessarily requires access to a Repo. I wonder if there could be a `dry-run` flag which would cause the action to parse the report, but refrain from actually creating the check run. This would allow the pipeline to continue.

**Comment by cobrabr** [comment]
I would also be very interested in this.

**Comment by Fed03** [comment]
👍  same problem

**Comment by bthornton191** [comment]
Is there a workaround for this? As far as I can tell, this issue makes the action unusable for jobs that run longer than 24 hours. Am I missing something?


## If I _DO NOT_ provide a token
```yaml
- name: Generate Set ${{ matrix.set }}${{ matrix.variant }} Test Report 
  uses: dorny/test-reporter@v1
  with:
    name: Results Set ${{ matrix.set }}${{ matrix.variant }}      
    path: qual/report/set_${{ matrix.set }}${{ matrix.variant }}.json    
    reporter: mocha-json
```

Any job that runs for more than 24 hours results in `Error: HttpError: Bad credentials`

![image](https://github.com/user-attachments/assets/2618eff4-2ba1-493d-aa01-e12e83eaabcb)

## If I _DO_ provide a token
```yaml
- name: Generate Set ${{ matrix.set }}${{ matrix.variant }} Test Report 
  uses: dorny/test-reporter@v1
  with:
    name: Results Set ${{ matrix.set }}${{ matrix.variant }}      
    path: qual/report/set_${{ matrix.set }}${{ matrix.variant }}.json    
    reporter: mocha-json
    token: ${{ secrets.TEST_REPORTER_TOKEN }}  
```
_ALL_ jobs result in `Error: HttpError: Resource not accessible by personal access token`


![image](https://github.com/user-attachments/assets/9dff10c7-f47a-47f7-aeeb-5e69afe99374)



I'm using a fine-grained token with 
✔**Read** access to metadata 
✔**Read** and **Write** access to actions, administration, and workflows 

![image](https://github.com/user-attachments/assets/49fa1be8-d39c-4bbb-bb66-43b668f645de)
