### ISSUE TITLE
Adhere to defaults.run working-directory?

### ISSUE THREAD

**Issue by AlexHedley** [dorny/test-reporter#152]
Should this adhere to the `defaults.run` `working-directory` and prepend?

```yml
defaults:
  run:
    working-directory: ./src/
```

With

```yml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
```

`path` becomes `./src/reports/jest-*.xml`

- [defaults.run](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#defaultsrun)
- [jobs.<job_id>.steps[*].run](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun)
