### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by dgokcin** [dorny/test-reporter#168]
Hello

We are having problems if this action is triggered from a dependabot pull request. I am attaching the error I am having below. Thanks!

![image](https://user-images.githubusercontent.com/33603535/162772449-d36072d1-922e-498f-9164-07f482e31a2a.png)

**Comment by tidusjar** [comment]
I'm also having this issue with forked PR's

**Comment by dgokcin** [comment]
@tidusjar apparently this was happening because of some missing permissions. I added this block to my workflow to fix it. you can check [the documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions).
```yaml
name: Build & Analyze Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
    - develop
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  lint:
#...
```

**Comment by hungrybear88** [comment]
i had to add these to the workflow

```
permissions:
  statuses: write
  checks: write
```

**Comment by tomkerkhove** [comment]
It's still not working for me though:
https://github.com/tomkerkhove/promitor/runs/6961162337?check_suite_focus=true

```yaml
jobs:
  verify_codebase:
    name: Verify Codebase
    runs-on: ubuntu-latest
    # Assign permissions for unit tests to be reported.
    # See https://github.com/dorny/test-reporter/issues/168
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
```

**Comment by JojOatXGME** [comment]
I am not using this Action, I noticed this issue because it is affecting a PR I created. I am not sure if granting more permissions to the build is a good solution. If I understand the [documentation of GitHub Actions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token) correctly, just granting this permission in the workflow file might not work for pull requests.

> You can use the permissions key to add and remove read permissions for forked repositories, but **typically you can't grant write access**.

I am wondering if it might be better if this action would use the annotations API of [`@actions/core`](https://github.com/actions/toolkit/tree/main/packages/core#annotations), instead of creating a new “check” using the REST interface? Maybe it could just be used as a fallback.

```javascript
core.error(ellipsis(message, 65535), {
  title: ellipsis(`${e.suiteName} ► ${e.testName}`, 255),
  file: e.path,
  startLine: e.line,
  endLine: e.line,
})
```

I haven't used this API, I only found it in the documentation. This API doesn't seem to allow to set the `raw_details` property of the annotation. Here is the corresponding code in the current implementation:

https://github.com/dorny/test-reporter/blob/e9fa2f582c0ebbe2e263fd18fad744d52e0b0203/src/report/get-annotations.ts#L71-L88

**Comment by DariuszPorowski** [comment]
> It's still not working for me though: https://github.com/tomkerkhove/promitor/runs/6961162337?check_suite_focus=true
> 
> ```yaml
> jobs:
>   verify_codebase:
>     name: Verify Codebase
>     runs-on: ubuntu-latest
>     # Assign permissions for unit tests to be reported.
>     # See https://github.com/dorny/test-reporter/issues/168
>     permissions:
>       statuses: write
>       checks: write
>       contents: write
>       pull-requests: write
> ```

@tomkerkhove if you have [Recommended setup for public repositories](https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories) configuration, then in the test-report.yml set:

```yaml
permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write
  actions: write  # <-- this was missing in you permissions
```
