### ISSUE TITLE
`dotnet-trx` reporter: "Error: No test report files were found"

### ISSUE THREAD

**Issue by dariusz-wozniak** [dorny/test-reporter#175]
I've started using test-reporter with the following code ([source](https://github.com/dariusz-wozniak/TestsAreFun/blob/main/.github/workflows/dotnet.yml)):

```yml
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit tests
      run: dotnet test --verbosity normal --no-build --filter "FullyQualifiedName~Tests.Unit" --logger "trx;LogFileName=test-results.trx"
    - name: Unit tests report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Unit tests
        path: test-results.trx
        reporter: dotnet-trx
```

But, I'm receiving the following error on the "Unit tests report" step (see [attempt](https://github.com/dariusz-wozniak/TestsAreFun/runs/6580988058?check_suite_focus=true)):

```
Check runs will be created with SHA=da3a5b4d795ed79cb4ed16b4c8377837fbd1e77e
Listing all files tracked by git
Found 171 files tracked by GitHub
Using test report parser 'dotnet-trx'
Creating test report Unit tests
  Warning: No file matches path test-results.trx
Error: No test report files were found
```

How can I fix that?

**Comment by sturman** [comment]
@dariusz-wozniak you need to specify path as wildcard
```yaml
...
    - name: Unit tests report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Unit tests
        path: '**/test-results.trx'
        reporter: dotnet-trx
...
```
I've just created a PR to your repository with fixed workflow

**Comment by dariusz-wozniak** [comment]
Thank you for the help, @sturman.

However, the merged PR fails:

```
Run dorny/test-reporter@v1
Check runs will be created with SHA=4ae3c23951059174c71107fc7030c7c6d6b55277
Listing all files tracked by git
Found 171 files tracked by GitHub
Using test report parser 'dotnet-trx'
Creating test report Unit tests
  Processing test results from tests/TestsAreFun.Tests.Acceptance/TestResults/test-results.trx
  Processing test results from tests/TestsAreFun.Tests.Approval/TestResults/test-results.trx
  Processing test results from tests/TestsAreFun.Tests.Integration/TestResults/test-results.trx
  Processing test results from tests/TestsAreFun.Tests.Load/TestResults/test-results.trx
  Processing test results from tests/TestsAreFun.Tests.Specification.LoFu/TestResults/test-results.trx
  Processing test results from tests/TestsAreFun.Tests.Specification.SpecFlow/TestResults/test-results.trx
  Processing test results from tests/TestsAreFun.Tests.Unit/TestResults/test-results.trx
  Processing test results from tests/TestsAreFun.Tests.Unit.Multitargeted/TestResults/test-results.trx
  Creating check run Unit tests
Error: Resource not accessible by integration
```

URL: https://github.com/dariusz-wozniak/TestsAreFun/runs/6852167174?check_suite_focus=true

Do you have any idea why it happens?

**Comment by sturman** [comment]
@dariusz-wozniak try to add these permissions
```yaml
permissions:
  id-token: write
  contents: read
  checks: write
```
