### ISSUE TITLE
Action fails when running in .NET3.1 SDK container

### ISSUE THREAD

**Issue by MonocleKelso** [dorny/test-reporter#181]
We have a fairly straight forward reusable workflow that takes a directory input, runs `dotnet test` in that directory, and uses this action to display the results.
```
name: Run .NET3 Tests

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
        description: The root directory of the SUT

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:3.1-focal
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test --logger "trx;LogFileName=test_results.trx"
        working-directory: ${{ inputs.directory }}/test
        name: Run Tests
      - uses: dorny/test-reporter@v1.5.0
        if: ${{ success() || failure() }}
        with:
          name: ${{ inputs.directory }} Test Results
          path: ${{ inputs.directory }}/test/TestResults/test_results.trx
          reporter: dotnet-trx
```

This consistently fails with the error
```
/usr/bin/git ls-files -z
  fatal: detected dubious ownership in repository
The process '/usr/bin/git' failed with exit code 128
```

We have another workflow that is identical except it uses `mcr.microsoft.com/dotnet/sdk:6.0` as the container. This workflow does not fail and displays the results as expected.

We've tested with both v1 and v1.5.0.

Both of these workflows are triggered off `pull_request` and use `dorny/paths-filter@v2` to determine what tests to run against the PR.

**Comment by MonocleKelso** [comment]
Circling back around to mention that the .NET7 container `mcr.microsoft.com/dotnet/sdk:7.0` also does not work. Weirdly enough, it was working fine last week but has started failing 100% of the time this week.

**Comment by HughMacdonald** [comment]
I've got 2 repositories that use the same container:

```
    runs-on: ubuntu-latest
    container: node:latest
```

One of them works fine, and the other has this error.

The one that comes up with this error also does some additional checking out of a dependency:
```
      - name: Checkout SWCore - main
        uses: actions/checkout@v3
        with:
          repository: MyOrganisation/MyRepository
          token: ${{ secrets.GH_PAT }}
          path: dependencies/MyRepository
          ref: develop
```

Any idea what could be causing this? The other repository (that doesn't have the dependency) doesn't have this issue.
