### ISSUE TITLE
Error: request to https://api.github.com/repos/xxx/check-runs failed, reason: tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by liu-shaojun** [dorny/test-reporter#182]
Hi experts,
I'm running job in the self-hosted runners, when I use scacap/action-surefire-report@v1 to publish report, I always get the error `Error: request to https://api.github.com/repos/intel-analytics/BigDL/check-runs failed, reason: tunneling socket could not be established, statusCode=407` https://github.com/intel-analytics/BigDL/runs/7836453943?check_suite_focus=true

```
    - name: Report
      uses: dorny/test-reporter@v1.5.0
      if: always()
      with:
        name: Maven Tests
        path: "scala/dllib/target/surefire-reports/TEST*.xml"
        reporter: java-junit
        fail-on-error: false
```
![image](https://user-images.githubusercontent.com/61072813/184777613-7685acda-14ca-4396-bcec-34e7f64bdbc5.png)

Where could the problem be?
