### ISSUE TITLE
Vitest junit - Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by michaelassaf** [dorny/test-reporter#187]
Using Vitest I would specify the following configuration for my [reporters](https://vitest.dev/config/#reporters):

```js
reporters: ['junit'],
outputFile: './report/integration-tests-results.json',
```

Failed Output:

```
Using test report parser 'jest-junit'
Creating test report Integration Tests Report
  Processing test results from ./report/integration-tests-results.xml
Error: Cannot read property 'time' of undefined
```

**Comment by ascott18** [comment]
Running into the same problem: https://github.com/IntelliTect/Coalesce/runs/7960417153?check_suite_focus=true

**Comment by SamKirkland** [comment]
The readme is outdated, the following worked for me.

my action yaml file
```yaml
name: "tests"
on:
  pull_request:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run test-ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: reports/jest-*.xml
          reporter: jest-junit
```


my package.json file
```json
{
  // some other stuff...
  "scripts": {
    "test": "jest",
    "test-ci": "jest --ci --reporters=default --reporters=jest-junit"
  },
  "dependencies": {
    "@actions/core": "^1.9.1",
    "@actions/exec": "^1.1.1",
    "@types/command-exists": "^1.2.0",
    "command-exists": "^1.2.9",
    "esbuild": "^0.15.6",
    "string-argv": "^0.3.1"
  },
  "devDependencies": {
    "@types/jest": "^28.0.0",
    "@types/node": "^18.7.9",
    "jest": "^28.0.0",
    "jest-junit": "^14.0.1",
    "jest-junit-reporter": "^1.1.0",
    "ts-jest": "^28.0.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "preset": "ts-jest",
    "testEnvironment": "node"
  },
  "jest-junit": {
    "outputDirectory": "reports",
    "outputName": "jest-junit.xml",
    "ancestorSeparator": " › ",
    "uniqueOutputName": "false",
    "suiteNameTemplate": "{filepath}",
    "classNameTemplate": "{classname}",
    "titleTemplate": "{title}"
  }
}
```
