### ISSUE TITLE
How to resolve "HttpError: request to .../check-runs failed, reason: self signed certificate in certificate chain" on GHES v3.3

### ISSUE THREAD

**Issue by BretStateham** [dorny/test-reporter#195]
We are using this action on an internal GHES v3.3 instance that has SSL configured using self-signed certificates.   We are using self-hosted macOS runners.

Even though the self-signed certificates are installed in the System Keychain on the macOS self-hosted runner, the action would fail with the error:

`HttpError: request to https://<server>/api/v3/repos/<org>/<repo>/check-runs failed, reason: self signed certificate in certificate chain`

To resolve the issue I was able to use the [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#node_extra_ca_certsfile) environment variable to point to a file with a copy of the self-signed certificates in `PEM` format.   

If you only have one self-signed certificate in your certificate chain, then the target file only needs contains that one certificate.  In my case we had a self-signed root CA certificate, and then an Intermediate CA certificate based off that root.  I had to combine the two into a single file, and then copy those into a path the self-hosted runner login could access.  For example:

```shell
cat my_root_ca.cer my_intermediate_ca.cer > my_combined.cer
mkdir ~/ca-certificates/extra
cp my_combined.cer ~/ca-certificates/extra
cp my_combined.cer 
```

Then I set the `NODE_EXTRA_CA_CERTS` variable in the action's `env` as such: 

```yaml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        env:
          NODE_EXTRA_CA_CERTS: /Users/myrunner/ca-certificates/extra/my_combined.cer
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
```

This resolved the issue for me on macOS.  We are also setting up Windows runners.  I'll report back if there are any differences for Windows.
