### ISSUE TITLE
No file matches path, but path is not what was specified

### ISSUE THREAD

**Issue by paynecrl97** [dorny/test-reporter#196]
See the output from this run:

![image](https://user-images.githubusercontent.com/2872984/192851297-935d94aa-3e4d-4e60-96ab-342f5f3deb3c.png)

Compare line 4 to line 30 and see that the path is different. Is this a bug, or am I doing something wrong?

The step YAML looks like this:

```
      # Check to see if the test results file exists so that we can condition the publishing of the test results:
      - name: Check whether or not the test results file exists
        id: test-results-verification
        if: always() # Even if previous steps have failed
        run: |
          if test -f "${{ runner.temp }}/junit.xml"; then
              echo "::set-output name=file-exists::true"
          fi

      # Publish the test results using an action from the marketplace:
      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: ${{ steps.test-results-verification.outputs.file-exists == 'true' && (success() || failure()) }} # Even if some tests failed
        with:
          name: Test results
          path: "${{ runner.temp }}/junit.xml"
          reporter: java-junit
```

(Note the second step is conditioned on the first step finding the file, and the second step is executing, so we know that the file is on disk where specified).
