### ISSUE TITLE
git error - "detected dubious ownership in repository"

### ISSUE THREAD

**Issue by HughMacdonald** [dorny/test-reporter#226]
I've got 2 repositories that use the same container:

```
    runs-on: ubuntu-latest
    container: node:latest
```

One of them works fine, and the other has this error:

```
  /usr/bin/git ls-files -z
  fatal: detected dubious ownership in repository at '/__w/MyRepository/MyRepository'
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /__w/MyRepository/MyRepository
```

The one that comes up with this error also does some additional checking out of a dependency:
```
      - name: Checkout MyRepository
        uses: actions/checkout@v3
        with:
          repository: MyOrganisation/MyRepository
          token: ${{ secrets.GH_PAT }}
          path: dependencies/MyRepository
          ref: develop
```

Any idea what could be causing this? The other repository (that doesn't have the dependency) doesn't have this issue.
