### ISSUE TITLE
Can't find artifact

### ISSUE THREAD

**Issue by gregsdennis** [dorny/test-reporter#234]
Just looking for some help.

I'm having a hard time getting this to find my artifacts.  I'm using the artifacts in other build steps, so I know they're there, but this action doesn't seem to be able to find them.

Build & Upload (after build):
```yaml
- name: Install dependencies
  run: dotnet restore
- name: Build
  run: dotnet build --configuration Release --no-restore
- name: Test
  run: dotnet test --no-restore --verbosity normal --logger:"trx;LogFileName=test-results.trx"
- name: Upload Unit Test Results
  if: always()
  uses: actions/upload-artifact@v2
  with:
    name: unit-test-results
    path: '**/*/test-results.trx'
```

Report Step:
```yaml
  test-report:
    runs-on: ubuntu-latest
    needs: build
    if: success() || failure()
    steps:
      - name: Download Artifacts  # I've tried with and without this, makes no difference
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - uses: dorny/test-reporter@v1
        with:
          artifact: unit-test-results       # artifact name
          name: Test Results (test)                 # Name of the check run which will be created
          path: '**/*/test-results.trx'                     # Path to test results (inside artifact .zip)
          reporter: dotnet-trx              # Format of test results
```

Report Step Output:
```
Run dorny/test-reporter@v1
  with:
    artifact: unit-test-results
    name: Test Results (test)
    path: **/*/test-results.trx
    reporter: dotnet-trx
    path-replace-backslashes: false
    list-suites: all
    list-tests: all
    max-annotations: 10
    fail-on-error: true
    only-summary: false
    token: ***
Action was triggered by pull_request: using SHA from head of source branch
Check runs will be created with SHA=a6f0b4ad7583baa6bf3a164d0c511b004f0af689
Fetching list of tracked files from GitHub
  Fetching tree f091f1105b88b341cc4be9716ae77957[2](https://github.com/gregsdennis/json-everything/actions/runs/4378590562/jobs/7663570386#step:3:2)fd70994
Found 791 files tracked by GitHub
Using test report parser 'dotnet-trx'
Warning: No artifacts found in run 4[3](https://github.com/gregsdennis/json-everything/actions/runs/4378590562/jobs/7663570386#step:3:3)78[5](https://github.com/gregsdennis/json-everything/actions/runs/4378590562/jobs/7663570386#step:3:5)905[6](https://github.com/gregsdennis/json-everything/actions/runs/4378590562/jobs/7663570386#step:3:6)2
Error: No test report files were found
```

[Example of failed build](https://github.com/gregsdennis/json-everything/actions/runs/4378262434/jobs/7663345790)
