### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by axc450** [dorny/test-reporter#244]
Can we get Python test support for this? I believe test results are usually in JUint/XML.
This action may already support it, but couldnt find anything to indicate it does.

Thanks!

**Comment by jnguyen75** [comment]
I've had success with `pytest` (which is compatible with `unittest`) by providing `--junit-xml` option and `--tb` to configure the traceback, which this test report uses to display more useful error messages.

**Comment by tfikler** [comment]
> I've had success with `pytest` (which is compatible with `unittest`) by providing `--junit-xml` option and `--tb` to configure the traceback, which this test report uses to display more useful error messages.

Can you please provide more information about how you managed to do it on using python pytest?

**Comment by jnguyen75** [comment]
> > I've had success with `pytest` (which is compatible with `unittest`) by providing `--junit-xml` option and `--tb` to configure the traceback, which this test report uses to display more useful error messages.
> 
> Can you please provide more information about how you managed to do it on using python pytest?

You just need to provide the `--junit-xml` argument as documented here: https://docs.pytest.org/en/7.2.x/how-to/output.html

Then provide that same path to the `path` input for this plugin.

**Comment by micmarc** [comment]
I am using this in a Django project with `unittest-xml-reporting`. I can see my tracebacks, but I have to scroll all the way to the bottom under "Annotations" and click the "Raw Output" button. (This is on V1; I have not gone to V2 yet.) It's not ideal, but it works fine for my purposes.

```yaml
    - name: (Django) Run Tests
      run: pipenv run python manage.py test

    - name: Generate Test Report
      uses: dorny/test-reporter@v1
      if: ${{ !cancelled() }}
      with:
        name: Test Results
        path: junit-report.xml
        reporter: java-junit
        fail-on-error: false
```
