### ISSUE TITLE
["list-tests: failed" is used *and* no actual test fails] -->> Warning is shown: "Test report summary exceeded limit of 65535 bytes and will be trimmed"

### ISSUE THREAD

**Issue by dejan-stojadinovic** [dorny/test-reporter#261]
Prologue: 
- could be related to #142
- we have GitHub limits on our mind:
-- https://github.com/marketplace/actions/test-reporter#github-limitations 
-- https://github.com/github/docs/issues/3765 
-- https://github.com/github/docs/issues/2403 

**Rationale (i.e. what are we trying to do here):** 
given a fact that warning about exceeded limit is shown for **_all_** test results we tried to limit number of results shown via `list-tests: failed` property, but limit is still exceeded. 

**Configuration:** 

```
    - name: Maven Tests results details
      uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: Maven Tests results details
        path: ${{ github.workspace }}/**/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
        list-tests: failed
```

**Test results summary:** 
![image](https://github.com/dorny/test-reporter/assets/122526527/a24da43d-1822-4b4e-8367-80d4470f41df)

Can't share full reproducer (repository code is not available to public).

**Few more snapshots:**

![image](https://github.com/dorny/test-reporter/assets/122526527/6305753d-8bae-41f5-81f4-72435a287dbc)

![image](https://github.com/dorny/test-reporter/assets/122526527/8fe10d47-cf1a-4f3d-9eee-6f0d8f825223)
