### ISSUE TITLE
"Error: HttpError: Resource not accessible by integration" during build process

### ISSUE THREAD

**Issue by marin-sigparser** [dorny/test-reporter#309]
We are using GitHub actions for our build process.

A part of our build process includes publishing our unit test results and we started getting this error today. 

![image](https://github.com/dorny/test-reporter/assets/141190080/3eb979d0-8ba4-46d9-9812-a01d76192b23)

**Comment by marin-sigparser** [comment]
We resolved this issue, it had to do with our GitHub permissions!

**Comment by michael-lowe-nz** [comment]
@marin-sigparser I got this today as well, what Github permissions fixed this for you?

**Comment by leandromsft** [comment]
> @marin-sigparser I got this today as well, what Github permissions fixed this for you?

You need to add this permissions in the workflow 

```
permissions:
  pull-requests: write
  contents: write
  statuses: write
  checks: write
  actions: write

```
