### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by louis-fri** [dorny/test-reporter#326]
When creating a test report, I get this error

```
Error: Processing test results from app/build/outputs/androidTest-results/connected/debug/TEST-test(AVD) - 10-_app-.xml failed
Error: TypeError: Cannot read properties of undefined (reading 'trim') 
```

My config
```
      - name: Generate android test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Android test results
          path: '**/build/outputs/androidTest-results/connected/debug/TEST-*.xml'
          reporter: java-junit
          fail-on-error: false
```
