### ISSUE TITLE
Test Reporter fails on workflow_run

### ISSUE THREAD

**Issue by snovak7** [dorny/test-reporter#343]
I have two step 

```yaml
...
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: "**/test-results*.trx"
...
```

and 

```yaml
name: report
on:
  workflow_run:
    workflows: 
      - build
    types:
      - completed
permissions: 
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: dotnet tests
          path: '**/test-results*.trx'
          reporter: dotnet-trx
```

trx file is successfully uploaded, inspecting the URL of test reporter action, it offers me to download the file, but the action fails

Report fails with error
HTTPError: Response code 400 (Authentication information is not given in the correct format. Check the value of Authorization header.)

Additional info: it worked, but after I bumped the version of the upload-artifacts (among other), somehow stopped working...

**Comment by abelbraaksma** [comment]
I noticed something similar. Here's one of my public repos where it goes wrong (with a similar config as you have): https://github.com/fsprojects/FSharp.Control.TaskSeq/pull/209

I suspect `actions/upload-artifact@v3` update to `actions/upload-artifact@v4` to be at the root of the issue. I'll try it with reverting that update and will report back.

**Comment by abelbraaksma** [comment]
Yep, this confirms it. The new `upload-artifacts@v4` either has bugs, or other changes, that prevents it from working with `test-reporter@v1`. I tested it here (https://github.com/fsprojects/FSharp.Control.TaskSeq/pull/212) with `v3`, which "just works", after all PRs with `v4` did not work:

![image](https://github.com/dorny/test-reporter/assets/16015770/bbae0095-51a3-47f6-8aa4-5ca063efa571)

**Comment by jozefizso** [comment]
Yes, this caused by different behavior in artifacts v4: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

**Comment by abelbraaksma** [comment]
@jozefizso are you aware of any way to fix this? Would it require bumping the major version here as well, or could it be made compatible with either?

**Comment by SapiensAnatis** [comment]
FYI I was able to make this work using a similar `workflow_run` setup by manually invoking the `download-artifact` action at v4:

```yaml
on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pattern: test-result-*
          merge-multiple: true
          run-id: ${{ github.event.workflow_run.id }}
      - name: Generate report
        uses: dorny/test-reporter@v1
        with:
          name: test report
          path: "*.trx"
          reporter: dotnet-trx
```

You have to generate your own `secrets.PERSONAL_ACCESS_TOKEN` for the `download-artifact` action to be able to download artifacts from outside its own workflow. The workflow to download from is specified using `${{ github.event.workflow_run.id }}`

**Comment by fernandopasik** [comment]
The github token @SapiensAnatis mentions needs to have the permission  actions:read on target repo.

@jozefizso @abelbraaksma  Would this mean that the fix for this problem in the action will need a token as well?

**Comment by abelbraaksma** [comment]
@fernandopasik I'm not sure, but it might very well be? If you want me to test a fix (I assume you'd do that in a new version), let me know and I can run a test through https://github.com/fsprojects/FSharp.Control.TaskSeq/issues/245).

**Comment by brianjmurrell** [comment]
@jozefizso [said previously](https://github.com/dorny/test-reporter/issues/343#issuecomment-1864054693):
> Yes, this caused by different behavior in artifacts v4: [github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/)

So given that it's 4 months on since the above comment, what's the plan to fix this?

How is this action in any way usable given this issue?  I.e. isn't is completely broken at this point now?  Or does this issue only affect certain use cases of this action?  If so, which use cases are still working?

**Comment by abelbraaksma** [comment]
>  I.e. isn't is completely broken at this point now?

It is actually `artifacts@v4` that is broken. They chose to, deliberately, make it backwards incompatible. And the guide to fix it isn't all that useful.

> So is simply downgrading the actions/upload-artifact action to v3 not enough to work around this issue?

If, when you upgraded to v4, you made the recommended changes in your actions, you need to undo those changes as well. Unfortunately, the people that published artifacts v4 didn't really bother to create an upgrade guide.

This is what happens when OSS folk makes a few too many assumptions that people are willing to update all their CI/CD flows just for a single version update (nothing against OSS in general, we all do our best, but a warning ahead and a guide would have been great).

**Comment by abelbraaksma** [comment]
TBF, it looks like it was actually resolved? So maybe your issue is related to something else entirely? https://github.com/selenide/selenide/issues/2704

**Comment by brianjmurrell** [comment]
> Simply downgrading should be enough.

It is not.  As [I previously said](https://github.com/dorny/test-reporter/issues/343#issuecomment-2046131955), it produces this failure:

```
Warning: No artifact matches /(Functional on .*) test-results/
```

when the artifact list clearly has artifacts that match the RE:

```
Functional on EL 8.8 test-results
Functional on EL 9 test-results
```

> Even if you applied fixes, it looks like any changes you did to accommodate v4, would work with v3. I think the main issue is same-named artifacts, which don't work anymore.

They don't have the same name though.  One has `8.8` in it where the other has `9`.

**Comment by djbrown** [comment]
See also #363

**Comment by JojOatXGME** [comment]
I was running into this issue today as well, although I don't have a repository using this action myself. The following configuration seems to work:

<details>
<summary>Show working example for test-report workflow (according to my tests)</summary>

```yaml
name: Test Report
run-name: >
  Test Report for ${{ github.event.workflow.name }}
  #${{ github.event.workflow_run.run_number }}:
  ${{ github.event.workflow_run.display_title }}
on:
  workflow_run:
    workflows: [Build]
    types: [completed]

# Permissions only have to be specified when set to be restricted by default.
# Otherwise, the workflow will have all necessary permissions by default.
# See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  checks: write
  # The documentation mentions that the following permissions is necessary to access other workflow runs.
  # However, the workflow seems to work even without this permission.
  # Maybe there is a special case which always allows access to the workflow run which triggered this run.
  actions: read

jobs:
  report:
    name: Test Report
    runs-on: ubuntu-latest

    steps:

      # We have to clone the repo as the test-reporter otherwise runs into an error.
      # See https://github.com/dorny/test-reporter/issues/131#issuecomment-2093880211
      - name: Fetch Sources
        uses: actions/checkout@v4

      # We have to manually download the artifact because dorny/test-reporter@v1
      # does not support artifacts uploaded by actions/upload-artifact@v4.
      # See https://github.com/dorny/test-reporter/issues/343
      - name: Download Test Reports
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Publish Test Reports as Annotations
        uses: dorny/test-reporter@v1
        with:
          name: "Unit Tests Report"
          path: "test-results-*/test-results/*/TEST-*.xml"
          reporter: java-junit

```

</details>

> You have to generate your own secrets.PERSONAL_ACCESS_TOKEN for the download-artifact action to be able to download artifacts from outside its own workflow.
> — https://github.com/dorny/test-reporter/issues/343#issuecomment-1872325556

> The github token @SapiensAnatis mentions needs to have the permission actions:read on target repo.
> — https://github.com/dorny/test-reporter/issues/343#issuecomment-1918804682

You can use the token provided by GitHub Actions (`github.token` or `secrets.GITHUB_TOKEN`). See my example above. The token has all the necessary permissions, `actions/download-artifact@v4` just doesn't use the token by default. Interestingly, even if you [restrict permissions by default](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token), you don't have to specify the permission `actions: read`. At least according to my tests. Maybe GitHub has implemented a special case for workflows triggered by `workflow_run`, so that they can always access the previous run that triggered this run.
