### ISSUE TITLE
No file matches path `build/phpunit/logs/*.xml`

### ISSUE THREAD

**Issue by bendavies** [dorny/test-reporter#400]
## Describe the bug
Hi, 

I'm receiving the Warning
> [!WARNING]  
> No file matches path `build/phpunit/logs/*.xml`

I am 100% that the report files exist at this `path`, but for some reason, this action is not finding them.

I cannot see where I am going wrong.

## To Reproduce
I list the logs before hand, so I am sure they exist.

See screenshot below showing the action can't find any logs.

```yml
      - name: "Run Tests"
        run: docker/bin/test-parallel.sh

      - name: "List logs"
        run: Run ls -l build/phpunit/logs

      - name: "Test Report"
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: PHPUnit Functional Tests
          path: build/phpunit/logs/*.xml
          reporter: java-junit
          max-annotations: 0
```

## Screenshots
<img width="1050" alt="image" src="https://github.com/dorny/test-reporter/assets/625392/1ed7a5b3-4661-4e07-beda-ddaef9179bb8">

Thankyou!
