### ISSUE TITLE
Testing .github/workflows/test-report.yml in public repos

### ISSUE THREAD

**Issue by brianjmurrell** [dorny/test-reporter#423]
## Describe
Hello.

Per your description for [Recommended setup for public repositories](https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories) how does the `artifact:` option know which triggering run to go fetch the artifacts from?

More to the point however, is do you have any advise on how one can test/debug their implementation of `.github/workflows/test-report.yml` in a PR -- without having to iterate on landing updates to make it work to the master branch?

I have tried adding `on:` -> `workflow_dispatch` to my `.github/workflows/test-report.yml` and then running the workflow manually but that manual run doesn't find artifacts to report on, I suppose because it has no linkage back to a `.github/workflows/ci.yml` that uploaded artifacts?

## Proposed solution
I suppose it's this (NPI): https://github.com/dorny/test-reporter/blob/c40d89d5e987cd80f3a32b3c233556e22bdca958/src/input-providers/artifact-provider.ts#L53-L56

When run from a `workflow_run` trigger, I am guessing that `this` is the triggering workflow run but when run from a `workflow_dispatch` trigger, it is it's _self_.

Any thoughts on being able to make this action simulate a `workflow_run` trigger by being able to provide a _run id_ value for https://github.com/dorny/test-reporter/blob/c40d89d5e987cd80f3a32b3c233556e22bdca958/src/input-providers/artifact-provider.ts#L55 when triggered from a `workflow_dispatch` with an input perhaps?

Or am I barking up the completely wrong tree here in trying to test my `.github/workflows/test-report.yml` before merging it to the default branch and there is a better way?

## Alternatives considered
Not sure of any other alternatives.

**Comment by JojOatXGME** [comment]
I haven't tried it, but wouldn't it be possible to create another workflow which triggers both of these workflows.

 1. Add the following trigger to both, `ci.yml` and `test-report.yml`.

    ```yaml
    on:
      workflow_call:
    ```

 2. Add a third workflow to test the report creation:

    ```yaml
    name: Test Creation of Test Report

    on:
      push:
        branches-ignore: [ 'master' ]
        paths:
          - .github/workflows/ci.yml
          - .github/workflows/test-report.yml
      workflow_dispatch:

    jobs:
      ci:

        uses: ./.github/workflows/ci.yml

      test-report:

        uses: ./.github/workflows/test-report.yml
    ```

As this would run both actions in the same top-level workflow, I would expect the fallback to the ID of the current workflow run to work just fine.
