### ISSUE TITLE
Using "v1" still serves 1.9.0 instead of 1.9.1

### ISSUE THREAD

**Issue by JojOatXGME** [dorny/test-reporter#444]
## Describe the bug

The following code block still uses version 1.9.0, although 1.9.1 has already been released.

```yaml
      - name: Test Report
        uses: dorny/test-reporter@v1
        continue-on-error: true
        with:
          artifact: /test-results-([^-]*)-(.*)/
          name: "Unit Tests Report: Gradle $1 @ $2"
          path: "test-results/*/TEST-*.xml"
          reporter: java-junit
          fail-on-empty: false
```

Here is the link to my build:
https://github.com/JojOatXGME/gradle-grammar-kit-plugin/actions/runs/9009127375/job/24752722668
You can see the version which has been used by the build by looking into the “Set up job”-step.

## Additional context
I noticed that this repository has both a branch and a tag called `v1`. The branch does not yet contain the new version. I guess the branch takes precedence. I also think the `v1` tag is new and did not exist for earlier releases.
