### ISSUE TITLE
badge-title not valid using @v1

### ISSUE THREAD

**Issue by salob** [dorny/test-reporter#546]
## Describe the bug
I get the following warning when using `badge-title`

```
Warning: Unexpected input(s) 'badge-title', valid inputs are ['artifact', 'name', 'path', 'path-replace-backslashes', 'reporter', 'list-suites', 'list-tests', 'max-annotations', 'fail-on-error', 'fail-on-empty', 'working-directory', 'only-summary', 'token']
```

## To Reproduce

Use the following

```
      # publish BDD test results to github
      - name: Publish Acceptance Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact: ''
          name: MS Tests
          path: '**/BDDTests.trx'
          reporter: 'dotnet-trx'
          badge-title: 'acceptance-tests'
```

## Expected behavior

badge-title is recognised
