### ISSUE TITLE
Main branch doesn't produce test check in workflow.

### ISSUE THREAD

**Issue by MichaelGlaive** [dorny/test-reporter#548]
## Describe the bug
No check is added to the workflow using main branch of the action.

## To Reproduce
Setup the following step, after running tests with nunit xml output (for example Unity can ONLY output nunit xml results):
```yaml
    - name: Test Report
      uses: dorny/test-reporter@main
      if: success() || failure()
      with:
        name: Tests
        path: UnityTests/results.xml
        reporter: dotnet-nunit
```

There's summary, but no check is added. If you use `v1` instead of `main`, then you have no access to `dotnet-nunit`, but the check would be present for `dotnet-trx` output for example.

## Expected behavior
Summary and check is added for `dotnet-nunit` on the `main` branch, or any other released branch.
