### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading '$')

### ISSUE THREAD

**Issue by alxmrtn-kroger** [dorny/test-reporter#551]
## Describe the bug
Running the test reporter with 2 reports: surefire and failsafe. It fails with the error
```
Using test report parser 'java-junit'
Creating test report Test Report
  Processing test results for check run Test Report
  Error: Processing test results from target/failsafe-reports/failsafe-summary.xml failed
Error: TypeError: Cannot read properties of undefined (reading '$')
```

## To Reproduce
Run unit and integration tests for java project. Configure generate test report as follows:
```yaml
- name: Generate Test Report
  uses: dorny/test-reporter@main
  with:
    name: Test Report
    path: target/surefire-reports/*.xml,target/failsafe-reports/*.xml
    reporter: java-junit
    fail-on-error: true
```

## Expected behavior
It's able to generate a report with multiple report xmls

**Comment by welsh** [comment]
Ran into same issue using this block:
```yml
- name: Publish Test Report
  uses: dorny/test-reporter@v1
  if: success() || failure()
  with:
    name: Maven Tests
    path: target/surefire-reports/*.xml,target/failsafe-reports/*.xml
    reporter: java-junit
```
So I tried splitting it up:
```yml
- name: Publish Unit Test Report
  uses: dorny/test-reporter@v1
  if: success() || failure()
  with:
    name: Maven Unit Tests
    path: target/surefire-reports/*.xml
    reporter: java-junit

- name: Publish Integration Test Report
  uses: dorny/test-reporter@v1
  if: success() || failure()
  with:
    name: Maven Integration Tests
    path: target/failsafe-reports/*.xml
    reporter: java-junit
```
However, it passed on the `Publish Unit Test Report` but on the `Publish Integration Test Report` received:
```
Using test report parser 'java-junit'
Creating test report Maven Integration Tests
  Processing test results for check run Maven Integration Tests
  Error: Processing test results from target/failsafe-reports/failsafe-summary.xml failed
Error: TypeError: Cannot read properties of undefined (reading '$')
```
I then realized it was actually erroring out on the `failsafe-summary.xml` which is just a summary file, it would be good if we could have something like an ignore filter or have the `java-junit` reporter ignore that file by default.

I updated my second block to:
```yml
- name: Publish Integration Test Report
  uses: dorny/test-reporter@v1
  if: success() || failure()
  with:
    name: Maven Integration Tests
    path: target/failsafe-reports/TEST-*.xml
    reporter: java-junit
```
And it worked.
