### ISSUE TITLE
Annotations aren't set propertly when using working-directory

### ISSUE THREAD

**Issue by lucasoares** [dorny/test-reporter#555]
## Describe the bug

I'm using test-reporter with `working-directory` to make reports of a .NET monorepo containing multiple sulutions and projects.

The git annotations for test failures are not created and linked with the files correctly.

## To Reproduce

My configuration (replaced variables with actual values):
```
   # .... other steps (like test)
    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: ${{ github.workflow  }} / Test Report
        path: **/*.trx
        reporter: dotnet-trx
        working-directory: src/Applications/Configurations
        token: <MY_TOKEN>
        fail-on-empty: 'false'
```

I made a change in the test to test failure annotations, making it to fail. The annotation was created but not linked to the correct file.

Screenshot from check run summary:

![Image](https://github.com/user-attachments/assets/a5c74eb6-724f-474d-b03d-589322795e11)

(ignore the blur, just to hide few things).

The annotation should be created in the path:
src/Applications/Configurations/T(...)t.I(...)s.Application.Configurations.UnitTests/Processors/ConfigurationProcessorTests.cs

Not in the:
T(...)t.I(...)s.Application.Configurations.UnitTests/Processors/ConfigurationProcessorTests.cs

When accessing the pull request itself, the annotation is never shown, only in the check summary page.

## Expected behavior

Annotations should appear on the Pull Request file diff.
