### ISSUE TITLE
Reporter input error when using 'dotnet-nunit'

### ISSUE THREAD

**Issue by blasco** [dorny/test-reporter#557]
## Describe the bug

Getting an error in reporter input when using 'dotnet-nunit':
```
Run dorny/test-reporter@v1.9.1
Check runs will be created with SHA=883648a662da3f8fd8b491f85f1617182992df67
Fetching list of tracked files from GitHub
Found 12763 files tracked by GitHub
Using test report parser 'dotnet-nunit'
Error: Error: Input variable 'reporter' is set to invalid value 'dotnet-nunit'
```

## To Reproduce
This is how I'm calling my action:
```
      - name: Publish Test Report
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          path: '*.xml'
          name: Unity Editor Tests
          reporter: dotnet-nunit
```

## Expected behavior
According to the source code, 'dotnet-unit' seems to be the correct value

From the main.ts:
```
  getParser(reporter: string, options: ParseOptions): TestParser {
    switch (reporter) {
      case 'dart-json':
        return new DartJsonParser(options, 'dart')
      case 'dotnet-nunit':
        return new DotnetNunitParser(options)
      case 'dotnet-trx':
        return new DotnetTrxParser(options)
      case 'flutter-json':
        return new DartJsonParser(options, 'flutter')
      case 'java-junit':
        return new JavaJunitParser(options)
      case 'jest-junit':
        return new JestJunitParser(options)
      case 'mocha-json':
        return new MochaJsonParser(options)
      case 'rspec-json':
        return new RspecJsonParser(options)
      case 'swift-xunit':
        return new SwiftXunitParser(options)
      default:
        throw new Error(`Input variable 'reporter' is set to invalid value '${reporter}'`)
    }
  }
```
