### ISSUE TITLE
Unable to generate report on junit.xml in github actions

### ISSUE THREAD

**Issue by srijanc** [dorny/test-reporter#563]
## Describe the bug
I am trying to run `php artisan test --log-junit tests/reports/junit.xml` which create a junit.xml file (attached is a text format due to permissions). The xml format is completely correct but the test report generated is empty (attached screenshot)

[junit.txt](https://github.com/user-attachments/files/19304820/junit.txt)

## To Reproduce
Workflow:
```
- name: PHPUnit Test Reporter
  uses: dorny/test-reporter@v2
  if: success() || failure()
  with:
    name: Laravel Test Results
    path: tests/reports/junit.xml
    reporter: java-junit
    fail-on-error: 'true'
```

## Expected behavior
Correct number of tests run, passed, skipped and failed

## Screenshots
Result:
![Image](https://github.com/user-attachments/assets/62f5d812-4bc0-49bf-b6a2-02ea4a613b12)

## Additional context
On using `mikepenz/action-junit-report` the generated output is as expected
```
- name: PHPUnit Test Reporter
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: tests/reports/junit.xml
          fail_on_failure: 'true'
```
