### ISSUE TITLE
Update to V2 brokes my update reports ci workflow

### ISSUE THREAD

**Issue by MikeSchulze** [dorny/test-reporter#565]
## Describe the bug
After upgrading to v2 the reports are not more attached to the original PR.
I use the publishing report workaround for forked repositories.

```
name: 'Publish Test Report'
on:
  workflow_run:
    workflows: ['ci-pr']  # runs after ci-pr workflow
    types:
      - completed
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'ID of the workflow run to download artifacts from.'
        required: true
        default: ''

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  publish-reports:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        godot-version: ['4.2', '4.2.1', '4.2.2', '4.3', '4.4']
        godot-status: ['stable']
       # include:
       #   - godot-version: '4.4'
       #     godot-status: 'dev3'

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      # publish API Tests results
      - name: Download API tests artifacts
        uses: actions/download-artifact@v4.2.1
        with:
          name: artifact_api_tests_Godot${{ matrix.godot-version }}-${{ matrix.godot-status }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: MikeSchulze/gdUnit4Net
          run-id: ${{ github.event.inputs.workflow_run_id || github.event.workflow_run.id }}

      - name: Publish API Test Results
        uses: dorny/test-reporter@v2.0.0
        with:
          name: report_api_tests_Godot${{ matrix.godot-version }}-${{ matrix.godot-status }}
          # using artifact to download is broken since download-artifact@v4 see https://github.com/dorny/test-reporter/issues/363
          # We do the download manually on step `Download artifacts`
          #artifact: artifact_gdUnit4_Godot${{ matrix.godot-version }}-${{ matrix.godot-status }}${{ matrix.godot-net }}
          path: './home/runner/work/gdUnit4Net/gdUnit4Net/test/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: 'false'
          fail-on-empty: 'false'
```

The reports now attached to the publish-report workflow and not to the original triggered pr.

## To Reproduce
- Run a PR with upload report artifacts
- Have a WF runs on the workflow to download the artifacts and pubilsh by using `dorny/test-reporter@v2.0.0`

The reports are attached now to the publish WF instead of the triggered WF

## Expected behavior
Should add reports as before to the source WF

## Screenshots

![Image](https://github.com/user-attachments/assets/5a8aa189-3d6a-4c78-b9cf-de9f0a8bbd70)

![Image](https://github.com/user-attachments/assets/ee7bd498-b750-46b8-862e-1d06b9fbdb18)
