### ISSUE TITLE
Validation Error "summary exceeds a maximum bytesize of 65535"

### ISSUE THREAD

**Issue by icnocop** [dorny/test-reporter#57]
Hi.

Thank you for test-reporter.

Configuration:
```
      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1.0.0
        if: always()
        with:
          name: Tests
          path: TestResults.trx
          reporter: dotnet-trx
          max-annotations: 50
```

Result:
```
<snipped>
Creating report summary
Generating check run summary
Creating annotations
Creating check run 'Tests' with conclusion 'failure'
##[error]Validation Failed: {"resource":"CheckRun","code":"custom","field":"summary","message":"summary exceeds a maximum bytesize of 65535"}
```

Full step log:
[15_Publish Unit Test Results.txt](https://github.com/dorny/test-reporter/files/5987203/15_Publish.Unit.Test.Results.txt)

Any ideas?

Is the trx too big?
Can I increase the maximum allowed size?

Thank you.
