### ISSUE TITLE
`fail-on-empty` when set to `false` should send a success check or produce an output that allows subsequent steps to do so

### ISSUE THREAD

**Issue by mezpahlan** [dorny/test-reporter#570]
## Describe

If I have

```
-   name: Test Results - Instrumentation tablet
    uses: dorny/test-reporter@v1.7.0
    with:
      name: Results UI Tests for tablet
      path: '**/ResultsTablet/JUnitReport.xml'
      reporter: java-junit
      fail-on-error: 'true'
      only-summary: 'true'
      fail-on-empty: 'false'
```

and for whatever reason my workflow upstream to this step didn't produce any test results (an example might be that we have calculated that no files of interested were modified only a `.md` file and we want to skip tests) then this step won't send a check - `success` _or_ `failure` at all. The problem is under normal conditions we might have this Dorny step as a required check gating our PRs and if we haven't run any tests (for whatever legitimate reason) then our PRs are "stuck" and require admin intervention.

## Proposed solution

Under the scenario where a user has `fail-on-empty: 'false'` send an "empty" check to Github along the lines of "No tests were run and `fail-on-error` was set to `false`". This allows any required check gating mechanism to pass without admin overrides.

I understand that might be a change in behaviour that you don't want to introduce in a rush but in that case at the very least could the [Output Parameters](https://github.com/dorny/test-reporter?tab=readme-ov-file#output-parameters) be modified to signify that `no-test-results-found` which would allow downstream steps to inspect this output and send the check themselves?

## Alternatives considered

We do something like this at my company as a workaround but it is a bit naff:

```
-   name: Test Results - Instrumentation (empty results)
    if: steps.find_results.outputs.FIND_RESULT == 'false'
    uses: actions/github-script@v6
    with:
      script: |
        await github.rest.checks.create({
        owner: context.repo.owner,
        repo: context.repo.repo,
        name: 'Results UI Tests for phone',
        head_sha: context.payload.pull_request.head.sha,
        status: 'completed',
        conclusion: 'success',
        output: {
          title: 'Results UI Tests for phone',
          summary: 'This check was skipped due empty results.',
        },
      });
```

Where `find_results` is a quick and dirty check in a preceding step to determine if any test related output has been written.
