### ISSUE TITLE
Unable to locate executable file: git

### ISSUE THREAD

**Issue by basilevs** [dorny/test-reporter#574]
## Describe the bug
I'm running tests in a container that has no Git installed. The action fails with a message:
> Error: Unable to locate executable file: git. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

## To Reproduce
Create and runa workflow:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: basilevs/ubuntu-rcptt:3.7.1 
      env:
        DISPLAY: :1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: m2repository
          path: |
            /root/.m2/repository
      - name: VNC
        run: vncserver $DISPLAY -localhost=1 -noxstartup -PasswordFile /root/.vnc/passwd
      - name: Build
        run: ./build.sh -DforceContextQualifier=`date '+%Y%M%d%H%M'` -DbuildUrl=file://`pwd` --errors --batch-mode --no-transfer-progress
      - name: Archive update site
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: repository
          path: 'repository/rcptt/target/repository/**'
      - name: Test Reporter
        if: always()
        uses: dorny/test-reporter@v2.0.0
        with:
          name: Self test
          reporter: java-junit
          path: "**/target/*-reports/*.xml"
```

## Expected behavior
No assumptions about test container are be made

## Additional context
A sample of failure can be viewed at https://github.com/eclipse-rcptt/org.eclipse.rcptt/actions/runs/14775651057
Adding: "max-annotations: 0" input does not help.
