### ISSUE TITLE
TRX file with no test cases throws an error

### ISSUE THREAD

**Issue by kpau** [dorny/test-reporter#61]
I am using the following configuration:
```yml
#   ...checkout, restore, build, etc.

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: Test Result
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: '**/*.trx'
        reporter: dotnet-trx
```

One of my projects has no tests and produces a TRX file without Test definitions:

```xml
<?xml version="1.0" encoding="utf-8"?>
<TestRun id="80e4c095-f726-4ab2-9441-416daa162672" name="..." runUser="..." xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2021-02-26T10:36:33.7131022+02:00" queuing="2021-02-26T10:36:33.7131029+02:00" start="2021-02-26T10:36:33.3278956+02:00" finish="2021-02-26T10:36:33.7139830+02:00" />
  <TestSettings name="default" id="863a1d8b-ee3b-45f9-86ee-1869bc4e889f">
    <Deployment runDeploymentRoot="..." />
  </TestSettings>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="0" executed="0" passed="0" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="..." outcome="Warning" timestamp="2021-02-26T10:36:33.6676104+02:00">
        <Text>No test is available in (...). Make sure that test discoverer &amp; executors are registered and platform &amp; framework version settings are appropriate and try again.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>
```

The following error is thrown:
```
Run dorny/test-reporter@v1
Check runs will be created with SHA=6b6aeb6092dc5c41605c5be7d7c3027dded62c59
Listing all files tracked by git
Found 37 files tracked by GitHub
Using test report parser 'dotnet-trx'
Creating test report .NET Tests
Error: trx.TestRun.TestDefinitions is not iterable
```

I changed the `path` and ignored that TRX file, and it all worked well.
From what I see the TRX file usually has `Results`, `TestDefinitions` and `TestEntries` elements inside the `TestRun` root element.

You can either check `TestRun.ResultSummary.Counters` if there are any tests, or just check if `TestDefinitions` is available before iterating it.
I would expect that the report will show the text under `ResultSummary.RunInfos.RunInfo.Text`.
