### ISSUE TITLE
Time reported as NaNms

### ISSUE THREAD

**Issue by rvernica** [dorny/test-reporter#633]
## Describe the bug

Integrated it into my workflow, but the time shows as *NaNms*. One occurrence of time is correctly reported, but two others are NaN. See screenshot.

## To Reproduce

Integrate like so:
```
      - name: Run tests
        run: |
          pytest --verbose --junitxml=report.xml

      - name: Publish Test Report
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@v2
        with:
          name: Pytest Results
          path: report.xml
          reporter: jest-junit
```
## Expected behavior
The time is reported correctly in all places.

## Screenshots
![Image](https://github.com/user-attachments/assets/dba13bd4-58e9-47d0-bcf2-6b4fa13591ca)
