### ISSUE TITLE
Test report doesn't appear in expected place in GitHub UI

### ISSUE THREAD

**Issue by tsimbalar** [dorny/test-reporter#67]
Hi,

thanks a lot for this Action 👍 

We currently have multiple GitHub Actions Workflows (`main.yaml` , `lint-yaml.yaml` etc ). 

When using the action inside of the `main.yaml`, the test results appear under the `lint-yaml` results 🤔 

Not 100% sure what is causing it 

![image](https://user-images.githubusercontent.com/160544/109523035-31e6b200-7aaf-11eb-949f-9d5c296e83f5.png)

our step, within `main.yaml` looks like 

```yaml
    - name: Report PR Test results
      uses: dorny/test-reporter@v1
      if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
      with:
        name: jest Tests
        path: reports/jest-*.xml
        reporter: jest-junit

```

Here is a (sanitized) output of the step : 

```
 1s
Run dorny/test-reporter@v1
  with:
    name: jest Tests
    path: reports/jest-*.xml
    reporter: jest-junit
    list-suites: all
    list-tests: all
    max-annotations: 10
    fail-on-error: true
    token: ***
  env:
     // snipped
Action was triggered by pull_request: using SHA from head of source branch
Check runs will be created with SHA=8d1d74409581269df26b4df491b55819597d9501
Listing all files tracked by git
  /usr/bin/git ls-files -z
  // ...
Found 190 files tracked by GitHub
Using test report parser 'jest-junit'
Creating test report jest Tests
  Processing test results from reports/jest-junit.xml
  Creating report summary
  Generating check run summary
  Creating annotations
  Creating check run with conclusion success
  Check run create response: 201
  Check run URL: https://api.github.com/repos/XXXX/YYYY/check-runs/2005347522
  Check run HTML: https://github.com/XXXX/YYYY/runs/2005347522

```
