### ISSUE TITLE
Clarification on if there is support for NUnit?

### ISSUE THREAD

**Issue by bhanson-techempower** [dorny/test-reporter#98]
Hi!

In the README summary, it lists NUnit support, but under the supported formats section I do not see an NUnit option.

Can you clarify if there is NUnit support? Thank you!

**Comment by dorny** [comment]
Hi!

Yes it's supported. You just need to get results in `trx` format instead of NUnit specific XML.

For example like this:
`dotnet test --logger "trx;LogFileName=test-results.trx"`

**Comment by bhanson-techempower** [comment]
Hi Michal!

Oh, I see now, thank you! 

Our tests use Unity Test Framework to generate NUnit3 XML files. Unfortunately, it only allows exporting in that format. Rereading the docs again it is pretty clear that the support is for a combination of .NET/NUnit and not NUnit alone. 👍

This looks really great though, nice work!

**Comment by dorny** [comment]
Adding support for another XML format is not so hard.
I will probably add direct support for NUnit once, but I can't promise any exact date.
Any contribution would be very welcome here :)

**Comment by Gakk** [comment]
@dorny I have moved build of several old .NET Framework project to GitHub, and runs NUnit Console Runner directly. I have not found a way for NUnit alone to generate results in TRX, neither any way to transform the default XML to TRX. If you were to implement support for NUnit XML directly this would be great 😃👍

**Comment by kf6kjg** [comment]
I got a workaround solved as follows:

```yaml
      - name: Install NUnit
        run: |
          nuget install NUnit.Console -Version 3.12.0

      - name: Fetch transform code
        run: |
          wget https://raw.githubusercontent.com/nunit/nunit-transforms/master/nunit3-junit/nunit3-junit.xslt
        shell: bash

      - name: Transform NUnit3 to JUnit
        run: |
          Get-ChildItem . -Filter test-results_*.xml | Foreach-Object {
            $xml = Resolve-Path $_.FullName
            $output = Join-Path ($pwd) ($_.BaseName + '_junit.xml')
            $xslt = New-Object System.Xml.Xsl.XslCompiledTransform;
            $xslt.Load("nunit3-junit.xslt");
            $xslt.Transform($xml, $output);
          }
        shell: pwsh

      - uses: dorny/test-reporter@v1.4.2
        with:
          name: "NUnit tests for $1"
          path: "*_junit.xml"
          reporter: jest-junit
```

You can see the current working workflow at https://github.com/HalcyonGrid/halcyon/blob/master/.github/workflows/test-report.yaml
